type ContactEnv = {
  API: string;
  PHONE: string;
  EMAIL: string;
  TELEGRAM: string;
  GITHUB: string;
  LINKEDIN: string;
  WHATSAPP: string;
  UPWORK: string;
};

type Env = {
  SITE_NAME: string;
  DEFAULT_LOCALE: string;
  TOTAL_SECTIONS: string;
  CONTACT: ContactEnv;
};

const {
  NEXT_PUBLIC_SITE_NAME,
  NEXT_PUBLIC_DEFAULT_LOCALE,
  NEXT_PUBLIC_TOTAL_SECTIONS,
  NEXT_PUBLIC_CONTACT_API,
  NEXT_PUBLIC_CONTACT_PHONE,
  NEXT_PUBLIC_CONTACT_EMAIL,
  NEXT_PUBLIC_CONTACT_TELEGRAM,
  NEXT_PUBLIC_CONTACT_GITHUB,
  NEXT_PUBLIC_CONTACT_LINKEDIN,
  NEXT_PUBLIC_CONTACT_WHATSAPP,
  NEXT_PUBLIC_CONTACT_UPWORK,
} = process.env;

export const env: Env = {
  SITE_NAME: NEXT_PUBLIC_SITE_NAME || 'Default Site',
  DEFAULT_LOCALE: NEXT_PUBLIC_DEFAULT_LOCALE || 'en',
  TOTAL_SECTIONS: NEXT_PUBLIC_TOTAL_SECTIONS || '7',

  CONTACT: {
    API: NEXT_PUBLIC_CONTACT_API || "",
    PHONE: NEXT_PUBLIC_CONTACT_PHONE || "",
    EMAIL: NEXT_PUBLIC_CONTACT_EMAIL || "",
    TELEGRAM: NEXT_PUBLIC_CONTACT_TELEGRAM || "",
    GITHUB: NEXT_PUBLIC_CONTACT_GITHUB || "",
    LINKEDIN: NEXT_PUBLIC_CONTACT_LINKEDIN || "",
    WHATSAPP: NEXT_PUBLIC_CONTACT_WHATSAPP || "",
    UPWORK: NEXT_PUBLIC_CONTACT_UPWORK || "",
  },
};
